image: gitpod/workspace-mysql

tasks:
  - init: npm i
    command: npm run start
  - init: mysql < resources/EC021_2020_1_NP1.sql

ports:
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
    - humao.rest-client@0.23.2:EcQzdx/LsXrhATjZFVSutw==
