POST http://localhost:3000/ec021/carro
Content-Type: application/json

{
  "marca": "Aston Martin",
  "modelo": "Borrachudo",
  "ano": 2077,
  "valor": 666666
}

###
GET http://localhost:3000/ec021/carro?id=4

### 
GET http://localhost:3000/ec021/carro?marca=Fiat

### 
GET http://localhost:3000/ec021/carro?marca=Fiat&modelo=Toro

### 
GET http://localhost:3000/ec021/carro?anoInicial=2019

### 
GET http://localhost:3000/ec021/carro?valorInicial=25000

